### PR TITLE
Markdown api

### PR DESCRIPTION
**Pull request by vrohatgi**
I added a Markdown API to convert the old gamescrafters website XML files to Markdown. I modified server.py with a dictionary mapping the old gamescrafter game ID's to the new GamesmanUni ID's and I added an app route specifically for the Markdown game instructions.

### CODE REVIEW

**Comment by vrohatgi** [comment]
@Ant1ng2 @sethlu 

Can you guys please review my changes by the next couple of days? Thank you so much!

**Comment by Ant1ng2** [comment]
Looks like a good idea to me, but why couldn't the instructions be placed in "/games/<gameid>" than "/instruction/<gameid>" as an attribute?

**Comment by vrohatgi** [comment]
> Looks like a good idea to me, but why couldn't the instructions be placed in "/games/<gameid>" than "/instructions/<gameid>" as an attribute?

@Ant1ng2 Good idea, I just fixed this!

**Comment by Ant1ng2** [comment]
It looks fine to me, I will merge it.

**Pull request merged**
